- src/pages/ValidateVoterPage.jsx
**Changes:**
* Set each field in state
* Check for ualberta email 
* Disable `Next` button until all 3 fields are filled correctly
**UI:**
* No visible change to the UI
> fix: form validation for ValidateVoterPage

- src/components/pages/ValidateVoterPage.jsx
- src/firebase/config/database.rules.json
**Changes:**
- retrieved ccid's from firebase and only added unique voters
- added .indexOn: ccid to rules for above point
**UI:**
- No visible UI changes.
> fix: block repeat voters

- README.md
- src/CONTRIBUTING.md
- src/components/pages/VotePage.jsx
**Changes**
- modified README.md to contain app info
- added CONTRIBUTING.md to be developer docs
- updated votepart's naming convention to be consistent with rest of app
**UI**
* No visible changes.
> chore(docs): app info & contributing.md

- src/App.js
- src/components/pages/VotePage.jsx
- src/firebase/firebase.js
**Changes**
- deleted duplicate firebaseConfig from firebase.js
- fixed import path in VotePage
- fixed import paths in App.js
**UI**
There are no visible UI changes.
> fix: delete duplicate firebaseConfig and update import paths

- src/App.js
- src/components/pages/VotePage.jsx
found some bug and fixed it due to the naming issues
> feat(context): found some error and fixed it due to naming issues

- CONTRIBUTING.md
- src/components/pages/ValidateVoterPage.jsx
- src/components/votepart/votepart.jsx
**Changes**
* added error handing function
* decompsed handleSubmit into
* checkVoterInMailingList(email)
* addVoter(email, voter)
* Added docs for how to push firebase rules upward
**UI**
* No visible UI changes.
> fix: email validation & checkVoterInMailingList skeleton code

- src/components/pages/ValidateVoterPage.jsx
- src/firebase/mailingList/importToFirestore.js
**Changes**
- allow revotes by using set() method
- delete duplicateVote error
- created onError function
**UI**
- No visible UI changes.
> feat: check voter in mailing list code

- src/App.js
- src/components/pages/IneligibleVoterScreen.jsx
- src/components/pages/ValidateVoterPage.jsx
**Changes**
* Used state to determine which screen to redirect to
* Redirects to either EligibleVoterScreen or IneligibleVoterScreen
**UI**
* No visible UI changes
> feat: link the valid fail and pass screens to ValidateVoterPage

- src/App.js
- src/components/Header.jsx
- src/components/pages/ValidateVoterPage.jsx
**Changes**
* Created a global header for all pages of the app
* Changed the height of the ValidateVoterPage from 100% to 90% to make room for the global header
**UI**
> Create menu bar

- src/components/pages/HomePage.jsx
**Changes**
- Added home page text
- Fixed width and height of segment and ada bot when resizing screen
**UI**
> fix: max-width and min-height for home page segment items

- src/components/pages/HomePage.jsx
**Changes**
- Moved the home page segment down to fit the ada bot hands
**UI**
> fix: ada bot hands holding up home page text

- src/components/constants.js
- src/components/pages/Results.jsx
**Changes**
- added placeholder cards for results screen
- created resultsCards constant in `constants.js` as placeholder
**UI**
> feat: results placeholder screen

- README.md
- src/components/pages/HomePage.jsx
**Changes**
- add the candidate list for future features.
**UI**
There are no visible UI changes.
> Add the candidate list for future features

- src/components/candidateHelper.js
**Changes**
- created a helper file called `candidateHelper.js` to return candidateList from firebase
**UI**
> feat: retrieve candidateList from firebase

- src/components/votepart/Candidate.jsx
- src/components/votepart/ListCandidates.jsx
- src/components/votepart/votepart.jsx
**Changes**
- fix radio button selection to allow selection of one candidate for each position
- fix styling of card (e.g. padding, centering radio button, placeholder image)
**UI**
> feat: voting for candidate

- src/components/Header.jsx
**Changes**
- added github icon/link to header
**UI**
> feat: add github icon/link to header

- src/components/votepart/ListCandidates.jsx
- src/components/votepart/votepart.jsx
**Changes**
- keep track of current vote for each position
- added submit  button
**UI**
* Added submit button at bottom of vote page. Fits width of the screen.
> feat: create and update vote

- src/components/votepart/votepart.jsx
**Changes**
- disable submit button until valid vote is made
**UI**
> feat: validate vote

- src/components/votepart/votepart.jsx
**Changes**
- cleared all console messages
- error 1: component key (fix down below)
- error 2: [source mapping ](https://stackoverflow.com/questions/36051891/esri-failed-to-parse-source-map)
- error 3: [timeout from extension](https://stackoverflow.com/questions/54126343/how-to-fix-unchecked-runtime-lasterror-the-message-port-closed-before-a-respon)
**UI**
* There are no visible UI changes
> fix: clear console errors

- src/components/ValidateVoter/LoadEligibility.jsx
- src/components/ValidateVoter/ValidateVoterPage.jsx
- src/components/votepart/Vote.jsx
**Changes**
- passed down `voter` from ValidateVoterPage
- validate that the voter went through the validation process
- upload the voter's set of votes to firebase
**UI**
- There are no visible UI changes
> feat: upload valid vote to realtime db

- src/components/votepart/Vote.jsx
**Changes**
- redirect to `Results` once a voter submits their vote
**UI**
> feat: redirect to Results page after vote

- src/components/votepart/Vote.jsx
**Changes**
- update the vote count for each candidate selected by the voter
**UI**
> feat: increment numOfVote after vote submit to cloud

- src/components/ValidateVoter/LoadEligibility.jsx
- src/components/ValidateVoter/ValidateVoterPage.jsx
- src/components/pages/HomePage.jsx
- src/components/votepart/ListCandidates.jsx
- src/components/votepart/Position.jsx
- src/components/votepart/Vote.jsx
**Changes**
- fix percent in progress bar
- fixed HomePage COVID-19 paragraph typo
- restricted 5 items per row
- fixed margin between position and its description
- added divider between each position
- converted vote page to Grid
**UI**
> fix: update UI of vote page

- src/components/constants.js
- src/components/votepart/Position.jsx
**Changes**
- added positions and their descriptions to constants.js
- changed the position description component from header to popup/tooltip.
- set font-size and max-width of popup/tooltip
**UI**
> <img width="1792" alt="Screen Shot 2020-03-28 at 12 38 23 AM" src="https://user-images.githubusercontent.com/23146829/77816926-7e9a5f80-708c-11ea-8110-218f3d952e46.png">
> feat: added position descriptions as tooltips on vote page

- src/components/votepart/Vote.jsx
**Changes**
-  add loader while vote page is loading
**UI**
> <img width="1792" alt="Screen Shot 2020-03-28 at 1 43 17 AM" src="https://user-images.githubusercontent.com/23146829/77818116-8b6f8100-7095-11ea-81e9-50725490faca.png">
> feat: add loader while vote page is loading

- src/components/pages/Results.jsx
**Changes**
- update numOfVotes in realtime every time Results page is navigated to results
- added winners2020 collection to firestore
**UI**
> No visible UI changes.
> feat: upload winners to firestore

- package-lock.json
- package.json
- src/components/pages/HomePage.jsx
**Changes**
- add new package to detect device type
- added Message component
- added margin-left to place in center
- tested using different old and new devices (Androids, iPhones, iPads)
**UI**
> ![Screen Shot 2020-04-02 at 10 57 59 PM](https://user-images.githubusercontent.com/23146829/78325777-e1c93d80-7535-11ea-9676-53c94415d9ae.png)
> feat: add warning message to mobile users

- src/firebase/candidateList/candidateList.json
> fix: added name field to candidateList.json

- src/components/constants.js
**Changes**
- made the keys the names
- added preferences
**UI**
> There are no visible UI changes
> feat: candidate keys and preferences

- src/components/VotePart/Candidate.jsx
- src/components/pages/CandidatesPage.jsx
**Changes**
- added candidate photos to the vote page
- made the photo appear on top rather than float on the right
- deleted console errors generated from the candidates page
**UI**
> ![Screen Shot 2020-04-03 at 3 42 10 AM](https://user-images.githubusercontent.com/23146829/78347084-27e5c780-755d-11ea-8424-bf8c8fc998d6.png)
> feat: added candidate photo

- src/components/ValidateVoter/ValidateVoterPage.jsx
**Changes**
- blocks users that haven't attended any ada's team events
**UI**
> There are no visible UI changes
> feat: block users that haven't attended ada's team event

- src/components/pages/HomePage.jsx
> fix: close voting

- src/components/ValidateVoter/ValidateVoterPage.jsx
- src/components/VotePart/Candidate.jsx
- src/components/constants.js
- src/components/pages/CandidatesPage.jsx
**Changes**
- delete unneeded print statements
- add reelected positions and candidates to `constants.js`
- render reelected candidates on `Candidates` page
**UI**
> ![Screen Shot 2020-04-04 at 10 16 21 PM](https://user-images.githubusercontent.com/23146829/78466734-f0dcf680-76c1-11ea-81d5-d83daa5e1f48.png)
> feat: show reelection candidates

- src/components/VotePart/ListCandidates.jsx
- src/components/VotePart/Vote.jsx
- src/firebase/candidateList/reelectionList.json
- src/firebase/importToFirestore.js
**Changes**
- clear console errors about unique keys 
- updated `onSelect` in `ListCandidates.jsx` to pass `candidateRanking` argument
- update state to update selection for each ranking
- upload `candidateList` to cloud firestore
**UI**
> There are no visible UI changes
> feat: reelection list

- src/components/VotePart/Vote.jsx
- src/components/constants.js
- src/components/pages/CandidatesPage.jsx
**Changes**
- set the reelect constant to false (it was set to true)
- also ensured that current react code reads from a `REELECT` constant in `constants.js`
**UI**
N/A
> chore: added REELECT constant + set it to false

- .gitignore
- package-lock.json
- package.json
- src/firebase/mailingList/filteredMailingList.json
- src/firebase/mailingList/jsonFilter.py
- src/firebase/mailingList/mailingList.json
**Changes**
- updated `mailingList.json` file to contain updated mailing list from MailChimp
- update `jsonFilter.py` to parse through the new formatted `mailingList.json` into its [expected format](https://github.com/adas-team/ElectionsApp/compare/master...HelenGezahegn:fixJsonFilter?expand=1#diff-55fa7471d4768ffccb2b588308cb9efcc5e7bc955c57a6873a766bc037d22deaR9).
- Ran `jsonFilter.py`, which updated `filteredMailingList.json`.
- addressed `react-dev-utils` [security issue](https://github.com/adas-team/ElectionsApp/security/dependabot/package.json/react-dev-utils/open).
**UI**
> fix: jsonFilter to use mailchimp exported csv

- .gitignore
- package-lock.json
- public/index.html
- src/components/VotePart/Candidate.jsx
- src/components/VotePart/Vote.jsx
- src/components/constants.js
**Changes**
- ran `npm run build` to generate build folder; added it to gitignore
- deleted the name format parsing in `Candidates`
- automatic linting changes
- Changed tab title to Ada’s Elections
- Changed website description to “Welcome to Ada’s Team Elections! 🎉 ”
**UI**
> ![image](https://user-images.githubusercontent.com/23146829/110936997-fa69d800-82ee-11eb-9ad8-1c1d60f55dde.png)
> fix: vote page to display images + preferences

- src/components/VotePart/Vote.jsx
**Changes**
- change voteMethod to `RADIO`
**UI**
> ![image](https://user-images.githubusercontent.com/23146829/110938064-87616100-82f0-11eb-8fb1-3932ca37c347.png)
> fix: change voteMethod to radio

- src/components/VotePart/ListCandidates.jsx
- src/firebase/candidateList/candidateList.json
**Changes**
- update to contain the full candidateList
- fix names to include space and be consistent
**UI**
> N/A
> fix: candidateList structure

- src/components/pages/CandidatesPage.jsx
**Changes**
- hide abstain card from main candidates page
**UI**
> There are no visible UI changes
> fix: hide abstain card from main candidates page

- src/components/ValidateVoter/LoadEligibility.jsx
- src/components/VotePart/ListCandidates.jsx
- src/components/pages/CandidatesPage.jsx
**Changes**
-  condense validation header to "One moment..." instead of "One moment please..."
- sort candidates page alphabetically
- list abstain card on the voting page (sort)
**UI**
> Candidates Page
> ![image](https://user-images.githubusercontent.com/23146829/110945861-72d69600-82fb-11eb-8856-9e3eafdbddb3.png)
> Voting Page
> ![image](https://user-images.githubusercontent.com/23146829/110945659-373bcc00-82fb-11eb-99b9-94a332df01da.png)
> feat: sort candidates page + list abstain card last on voting page

- package-lock.json
- src/components/helper.js
- src/components/pages/Results.jsx
- src/firebase/candidateList/winnersList.json
- src/firebase/importToFirestore.js
**Changes**
- created `winners.json` 
- added winners command to `importToFirebase`
- rendered winners in `Results.jsx` 
**UI**
> ![image](https://user-images.githubusercontent.com/23146829/112033623-39740680-8b03-11eb-8390-4c01bc5c46ca.png)
> feat: display winners

- src/components/VotePart/Candidate.jsx
- src/components/constants.js
- src/components/pages/HomePage.jsx
- src/components/pages/Results.jsx
**Changes**
- created constants to get year using a function
- added css to fix stretching
**UI**
> feat: created constants to get year and fixed image stretching

- src/components/pages/CandidatesPage.jsx
- src/components/pages/Results.jsx
> feat: added preferences list to Candidates and fixed Results page 

- src/components/VotePart/Candidate.jsx
> feat: changing the aspect ratio of the photos

- src/components/pages/Results.jsx
- src/firebase/candidateList/winnersList.json
> chore: manually added winners
